# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/conice/"
[social.params]
icon = "brand-github"

[[social]]
identifier = "bilibili"
name = "BiliBili"
url = "https://x.com/AndMogo"
[social.params]
icon = "brand-bilibili"

[[social]]
identifier = "youtube"
name = "YouTube"
url = "https://x.com/AndMogo"
[social.params]
icon = "brand-youtube"

[[social]]
identifier = "tiktok"
name = "TikTok"
url = "https://x.com/AndMogo"
[social.params]
icon = "brand-tiktok"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://x.com/AndMogo"
[social.params]
icon = "brand-instagram"

[[social]]
identifier = "facebook"
name = "Facebook"
url = "https://x.com/AndMogo"
[social.params]
icon = "brand-facebook"

[[social]]
identifier = "threads"
name = "Threads"
url = "https://x.com/AndMogo"
[social.params]
icon = "brand-threads"

[[social]]
identifier = "discord"
name = "Discord"
url = "https://x.com/AndMogo"
[social.params]
icon = "brand-discord"

[[social]]
identifier = "facebook"
name = "Facebook"
url = "https://x.com/AndMogo"
[social.params]
icon = "brand-facebook"

[[social]]
identifier = "email"
name = "Email"
url = "https://x.com/AndMogo"
[social.params]
icon = "mail"